spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
        lower-case-service-id: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**, /api/v1/user/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notification/**

security:
  public-paths:
    - /api/v1/auth/**
    - /fallback
    - /actuator/**

secreteJwtString: ${JWT_SECRET:adfnkgndsfvndnscsodvndvndkvnknvkdfsnkjdsnvdfnnd}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        sliding-window-type: COUNT_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
    instances:
      defaultCircuitBreaker:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2s
