spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**,/api/v1/user/**,/api/v1/address/**
        - id: notification-service-route
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**
        - id: product-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
        - id: category-service-route
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/v1/category/**
        - id: cart-service-route
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/cart/**
        - id: inventory-service-route
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
        - id: order-service-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
        - id: payment-service-route
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
        - id: shipping-service-route
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/v1/shipping/**

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

security:
  public-paths:
    - /api/v1/auth/**
    - /fallback
    - /actuator/**

secreteJwtString: ${JWT_SECRET:adfnkgndsfvndnscsodvndvndkvnknvkdfsnkjdsnvdfnnd}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        sliding-window-type: COUNT_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
    instances:
      defaultCircuitBreaker:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true