spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
        lower-case-service-id: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
      default-filters:
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            #fallbackUri: forward:/fallback
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/user/**, /api/v1/address/**
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/v1/product/**
        - id: CATEGORY-SERVICE
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/api/v1/category/**
        - id: CART-SERVICE
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/v1/cart/**
        - id: INVENTORY-SERVICE
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
        - id: ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order/**
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/v1/payment/**
        - id: SHIPPING-SERVICE
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/v1/shipping/**

security:
  public-paths:
    - /api/v1/auth/**
    - /fallback
    - /actuator/**

secreteJwtString: ${JWT_SECRET:adfnkgndsfvndnscsodvndvndkvnknvkdfsnkjdsnvdfnnd}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        sliding-window-type: COUNT_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5
    instances:
      defaultCircuitBreaker:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 10s
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2s
