eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost    

microservice:
  user-service:
    endpoints:
      endpoint:
        uri: http://user-service/api/v1/**
