spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}

user:
  api:
    url: http://user-service

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

#Actuator endpoints
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers, prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      # Default to localhost for IDE, override via ENV var in Docker Compose
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}

# Loki URL needs to point to the Loki container
loki:
  # Default to localhost for IDE, override via ENV var in Docker Compose
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}

#Reselience4j properties
resilience4j:
  circuitbreaker:
    instances:
      user:
        registerHealthIndicator: true
        sliding-window-type: COUNT_BASED
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        minimum-number-of-calls: 5

  #reselience4j timeout properties
  timelimiter:
    instances:
      user:
        timeoutDuration: 3s

  # reselience4j Retry properties
  retry:
    instances:
      user:
        maxAttempts: 3
        waitDuration: 2s
          #enableExponentialBackoff: true
          #exponentialBackoffMultiplier: 2
          #retryExceptions:
          # - java.io.IOException
        #- java.util.concurrent.TimeoutException

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [product-service,%X{traceId:-},%X{spanId:-}]"